language: r
r:
  - oldrel
  - release
  - devel

#######################################
# install gsl-devel for topicmodels
#######################################
before_script:
  - export NOT_CRAN=false
  - sudo apt-get install libgsl0-dev

############################
# better caching for Travis
# See : https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
###########################
cache:
  - ccache
addons:
  apt:
    packages:
     - ccache
