language: r
r:
  - release
  - devel

r_check_args: '--as-cran'
warnings_are_errors: true

matrix:
  include:
  - os: linux
    dist: trusty
    apt_packages:
       - ccache
       - libgsl-dev
       - gsl-bin
  - os: osx
    osx_image: xcode7.3 # close from CRAN
    brew_packages:
      - gsl
      - ccache

############################
# better caching for Travis
# See : https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
###########################
cache:
  - ccache

