language: r
r:
  - release
  - devel

os:
  - linux
  - osx
  - windows

#######################################
# install gsl-devel for topicmodels
#######################################
before_script:
  - export NOT_CRAN=false
  - sudo apt-get install gsl-bin libgsl0-dev libgsl-dev

############################
# better caching for Travis
# See : https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
###########################
cache:
  - ccache
addons:
  apt:
    packages:
     - ccache
     - libgsl0-dev
